{
 "title": "Virtual Machines",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Virtualization Support (libvirtd)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "libvirt_up" }
   ]
  },
  {
   "title": "VM CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(libvirt_domain_info_cpu_time_seconds_total{domain!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "System Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"ext4\"} - node_filesystem_free_bytes{fstype=\"ext4\"}) / node_filesystem_size_bytes{fstype=\"ext4\"}  * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)" }
   ]
  },
  {
   "title": "Running Virtual Machines",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(libvirt_domain_info_virtual_cpus{domain!=\"\"}) > 0)",
     "legendFormat": "virtual machines"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (domain) (rate(libvirt_domain_info_cpu_time_seconds_total{domain!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (domain)(libvirt_domain_info_memory_usage_bytes{domain!=\"\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Virtual Machines Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (domain,source_bridge) (rate(libvirt_domain_interface_stats_receive_bytes_total{domain!=\"\"}[1m]))",
     "legendFormat": "{{ domain }}: {{ source_bridge }}"
    }
   ]
  },
  {
   "title": "Virtual Machines Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (domain,source_bridge) (rate(libvirt_domain_interface_stats_transmit_bytes_total{domain!=\"\"}[1m]))",
     "legendFormat": "{{ domain }}:{{ source_bridge }}"
    }
   ]
  },
  {
   "title": "Virtual Machines I/O Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (domain,target_device) (rate(libvirt_domain_block_stats_read_bytes_total{domain!=\"\"}[1m]))",
     "legendFormat": "{{ domain }} - {{ target_device }}"
    }
   ]
  },
  {
   "title": "Virtual Machines I/O Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (domain,target_device) (rate(libvirt_domain_block_stats_write_bytes_total{domain!=\"\"}[1m]))",
     "legendFormat": "{{ domain }} - {{ target_device }}"
    }
   ]
  }
 ]
}